@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

rectangle AddIsSick
rectangle Apothecary
rectangle ApothecaryHandler
rectangle BlackSmith
rectangle BlackSmithHandler
rectangle ColonySimulatorContext
rectangle ColonySimulatorContextModelSnapshot
rectangle ConsequenceOverview
rectangle Crops
rectangle Effect
rectangle Farmer
rectangle FarmerHandler
rectangle FightingThreat
rectangle FightingThreatEffect
rectangle Gender
rectangle Herbs
rectangle IApothecaryHandler
rectangle IBlackSmithHandler
rectangle IFarmerHandler
rectangle IMedicHandler
rectangle IPersonActivity
rectangle IProfessionHandler
rectangle IResourceHandler
rectangle IThreatHandler
rectangle ITimberHandler
rectangle ITraderHandler
rectangle Medic
rectangle MedicHandler
rectangle Medicine
rectangle NaturalEffect
rectangle NaturalThreat
rectangle Person
rectangle PlagueEffect
rectangle PlagueThreat
rectangle PopCounter
rectangle ProbabilityConsts
rectangle ProfessionHandler
rectangle ProfessionSeeder
rectangle ProfessionsOverview
rectangle Proffesion
rectangle Program
rectangle Resource
rectangle ResourceHandler
rectangle ResourceSeeder
rectangle StartupService
rectangle Threat
rectangle ThreatSeeder
rectangle Threathandler
rectangle ThreatsOverview
rectangle Timber
rectangle TimberHandler
rectangle Trader
rectangle TraderHandler
rectangle Weaponry
rectangle Wood
rectangle Year
rectangle init

AddIsSick                            -[#3574f0,plain]->>  ColonySimulatorContext              
Apothecary                           -[#24a394,dashed]-^  Person                              
Apothecary                           -[#24a394,dashed]-^  Proffesion                          
ApothecaryHandler                    -[#3574f0,plain]->>  Herbs                               
ApothecaryHandler                    -[#24a394,dashed]-^  IApothecaryHandler                  
ApothecaryHandler                    -[#24a394,dashed]-^  IPersonActivity                     
ApothecaryHandler                    -[#3574f0,plain]->>  Threat                              
BlackSmith                           -[#24a394,dashed]-^  Person                              
BlackSmith                           -[#24a394,dashed]-^  Proffesion                          
BlackSmithHandler                    -[#24a394,dashed]-^  IBlackSmithHandler                  
BlackSmithHandler                    -[#24a394,dashed]-^  IPersonActivity                     
BlackSmithHandler                    -[#3574f0,plain]->>  Threat                              
BlackSmithHandler                    -[#3574f0,plain]->>  Weaponry                            
BlackSmithHandler                    -[#3574f0,plain]->>  Wood                                
ColonySimulatorContext               -[#3574f0,plain]->>  Apothecary                          
ColonySimulatorContext               -[#3574f0,plain]->>  BlackSmith                          
ColonySimulatorContext               -[#f2c55c,plain]-*  ColonySimulatorContext              
ColonySimulatorContext               -[#3574f0,plain]->>  Crops                               
ColonySimulatorContext               -[#3574f0,plain]->>  Farmer                              
ColonySimulatorContext               -[#3574f0,plain]->>  FightingThreat                      
ColonySimulatorContext               -[#3574f0,plain]->>  Herbs                               
ColonySimulatorContext               -[#3574f0,plain]->>  Medic                               
ColonySimulatorContext               -[#3574f0,plain]->>  Medicine                            
ColonySimulatorContext               -[#3574f0,plain]->>  NaturalThreat                       
ColonySimulatorContext               -[#3574f0,plain]->>  PlagueThreat                        
ColonySimulatorContext               -[#3574f0,plain]->>  Timber                              
ColonySimulatorContext               -[#3574f0,plain]->>  Trader                              
ColonySimulatorContext               -[#3574f0,plain]->>  Weaponry                            
ColonySimulatorContext               -[#3574f0,plain]->>  Wood                                
ColonySimulatorContextModelSnapshot  -[#3574f0,plain]->>  ColonySimulatorContext              
Crops                                -[#24a394,dashed]-^  Resource                            
Farmer                               -[#24a394,dashed]-^  Person                              
Farmer                               -[#24a394,dashed]-^  Proffesion                          
FarmerHandler                        -[#3574f0,plain]->>  Crops                               
FarmerHandler                        -[#24a394,dashed]-^  IFarmerHandler                      
FarmerHandler                        -[#24a394,dashed]-^  IPersonActivity                     
FarmerHandler                        -[#3574f0,plain]->>  Threat                              
FightingThreat                       -[#24a394,dashed]-^  Threat                              
FightingThreatEffect                 -[#24a394,dashed]-^  Effect                              
IApothecaryHandler                   -[#3574f0,plain]->>  Herbs                               
IApothecaryHandler                   -[#24a394,dashed]-^  IPersonActivity                     
IBlackSmithHandler                   -[#24a394,dashed]-^  IPersonActivity                     
IBlackSmithHandler                   -[#3574f0,plain]->>  Weaponry                            
IBlackSmithHandler                   -[#3574f0,plain]->>  Wood                                
IFarmerHandler                       -[#3574f0,plain]->>  Crops                               
IFarmerHandler                       -[#24a394,dashed]-^  IPersonActivity                     
IMedicHandler                        -[#24a394,dashed]-^  IPersonActivity                     
IMedicHandler                        -[#3574f0,plain]->>  Medicine                            
IPersonActivity                      -[#3574f0,plain]->>  Threat                              
IProfessionHandler                   -[#3574f0,plain]->>  Effect                              
IProfessionHandler                   -[#3574f0,plain]->>  Proffesion                          
IResourceHandler                     -[#3574f0,plain]->>  Person                              
IThreatHandler                       -[#3574f0,plain]->>  Effect                              
IThreatHandler                       -[#3574f0,plain]->>  Proffesion                          
IThreatHandler                       -[#3574f0,plain]->>  Threat                              
ITimberHandler                       -[#24a394,dashed]-^  IPersonActivity                     
ITimberHandler                       -[#3574f0,plain]->>  Wood                                
ITraderHandler                       -[#3574f0,plain]->>  Herbs                               
ITraderHandler                       -[#24a394,dashed]-^  IPersonActivity                     
ITraderHandler                       -[#3574f0,plain]->>  Medicine                            
ITraderHandler                       -[#3574f0,plain]->>  Weaponry                            
ITraderHandler                       -[#3574f0,plain]->>  Wood                                
Medic                                -[#24a394,dashed]-^  Person                              
Medic                                -[#24a394,dashed]-^  Proffesion                          
MedicHandler                         -[#24a394,dashed]-^  IMedicHandler                       
MedicHandler                         -[#24a394,dashed]-^  IPersonActivity                     
MedicHandler                         -[#3574f0,plain]->>  Medicine                            
MedicHandler                         -[#3574f0,plain]->>  Threat                              
Medicine                             -[#24a394,dashed]-^  Resource                            
NaturalEffect                        -[#24a394,dashed]-^  Effect                              
NaturalThreat                        -[#24a394,dashed]-^  Threat                              
Person                               -[#955ae0,plain]->>  Gender                              
Person                               -[#3574f0,plain]->>  Gender                              
PlagueEffect                         -[#24a394,dashed]-^  Effect                              
PlagueThreat                         -[#24a394,dashed]-^  Threat                              
ProfessionHandler                    -[#3574f0,plain]->>  Effect                              
ProfessionHandler                    -[#f2c55c,plain]-*  IApothecaryHandler                  
ProfessionHandler                    -[#5fad65,dotted]->>  IApothecaryHandler                  
ProfessionHandler                    -[#f2c55c,plain]-*  IBlackSmithHandler                  
ProfessionHandler                    -[#5fad65,dotted]->>  IBlackSmithHandler                  
ProfessionHandler                    -[#f2c55c,plain]-*  IFarmerHandler                      
ProfessionHandler                    -[#5fad65,dotted]->>  IFarmerHandler                      
ProfessionHandler                    -[#5fad65,dotted]->>  IMedicHandler                       
ProfessionHandler                    -[#f2c55c,plain]-*  IMedicHandler                       
ProfessionHandler                    -[#24a394,dashed]-^  IProfessionHandler                  
ProfessionHandler                    -[#f2c55c,plain]-*  ITimberHandler                      
ProfessionHandler                    -[#5fad65,dotted]->>  ITimberHandler                      
ProfessionHandler                    -[#5fad65,dotted]->>  ITraderHandler                      
ProfessionHandler                    -[#f2c55c,plain]-*  ITraderHandler                      
ProfessionHandler                    -[#3574f0,plain]->>  Proffesion                          
ProfessionSeeder                     -[#3574f0,plain]->>  Apothecary                          
ProfessionSeeder                     -[#3574f0,plain]->>  BlackSmith                          
ProfessionSeeder                     -[#5fad65,dotted]->>  ColonySimulatorContext              
ProfessionSeeder                     -[#3574f0,plain]->>  ColonySimulatorContext              
ProfessionSeeder                     -[#f2c55c,plain]-*  ColonySimulatorContext              
ProfessionSeeder                     -[#3574f0,plain]->>  Farmer                              
ProfessionSeeder                     -[#3574f0,plain]->>  Gender                              
ProfessionSeeder                     -[#3574f0,plain]->>  Medic                               
ProfessionSeeder                     -[#3574f0,plain]->>  Person                              
ProfessionSeeder                     -[#3574f0,plain]->>  PopCounter                          
ProfessionSeeder                     -[#5fad65,dotted]->>  PopCounter                          
ProfessionSeeder                     -[#f2c55c,plain]-*  PopCounter                          
ProfessionSeeder                     -[#3574f0,plain]->>  Proffesion                          
ProfessionSeeder                     -[#3574f0,plain]->>  Timber                              
ProfessionSeeder                     -[#3574f0,plain]->>  Trader                              
ProfessionsOverview                  -[#3574f0,plain]->>  Apothecary                          
ProfessionsOverview                  -[#3574f0,plain]->>  BlackSmith                          
ProfessionsOverview                  -[#3574f0,plain]->>  Farmer                              
ProfessionsOverview                  -[#3574f0,plain]->>  Medic                               
ProfessionsOverview                  -[#3574f0,plain]->>  Timber                              
ProfessionsOverview                  -[#3574f0,plain]->>  Trader                              
Proffesion                           -[#24a394,dashed]-^  Person                              
Program                              -[#3574f0,plain]->>  ColonySimulatorContext              
Program                              -[#3574f0,plain]->>  PopCounter                          
Program                              -[#3574f0,plain]->>  ProfessionSeeder                    
Program                              -[#3574f0,plain]->>  ResourceSeeder                      
Program                              -[#3574f0,plain]->>  StartupService                      
Program                              -[#3574f0,plain]->>  ThreatSeeder                        
Program                              -[#3574f0,plain]->>  Year                                
ResourceHandler                      -[#24a394,dashed]-^  IResourceHandler                    
ResourceHandler                      -[#3574f0,plain]->>  Person                              
ResourceSeeder                       -[#5fad65,dotted]->>  ColonySimulatorContext              
ResourceSeeder                       -[#3574f0,plain]->>  ColonySimulatorContext              
ResourceSeeder                       -[#f2c55c,plain]-*  ColonySimulatorContext              
ResourceSeeder                       -[#3574f0,plain]->>  Crops                               
ResourceSeeder                       -[#3574f0,plain]->>  Herbs                               
ResourceSeeder                       -[#3574f0,plain]->>  Medicine                            
ResourceSeeder                       -[#3574f0,plain]->>  Resource                            
ResourceSeeder                       -[#3574f0,plain]->>  Weaponry                            
ResourceSeeder                       -[#3574f0,plain]->>  Wood                                
StartupService                       -[#3574f0,plain]->>  Year                                
StartupService                       -[#f2c55c,plain]-*  Year                                
StartupService                       -[#5fad65,dotted]->>  Year                                
ThreatSeeder                         -[#5fad65,dotted]->>  ColonySimulatorContext              
ThreatSeeder                         -[#f2c55c,plain]-*  ColonySimulatorContext              
ThreatSeeder                         -[#3574f0,plain]->>  PlagueThreat                        
ThreatSeeder                         -[#f2c55c,plain]-*  PopCounter                          
ThreatSeeder                         -[#3574f0,plain]->>  PopCounter                          
ThreatSeeder                         -[#5fad65,dotted]->>  PopCounter                          
ThreatSeeder                         -[#3574f0,plain]->>  Threat                              
Threathandler                        -[#3574f0,plain]->>  Effect                              
Threathandler                        -[#24a394,dashed]-^  IThreatHandler                      
Threathandler                        -[#3574f0,plain]->>  Proffesion                          
Threathandler                        -[#3574f0,plain]->>  Threat                              
ThreatsOverview                      -[#3574f0,plain]->>  Threat                              
Timber                               -[#24a394,dashed]-^  Person                              
Timber                               -[#24a394,dashed]-^  Proffesion                          
TimberHandler                        -[#24a394,dashed]-^  IPersonActivity                     
TimberHandler                        -[#24a394,dashed]-^  ITimberHandler                      
TimberHandler                        -[#3574f0,plain]->>  Threat                              
TimberHandler                        -[#3574f0,plain]->>  Wood                                
Trader                               -[#24a394,dashed]-^  Person                              
Trader                               -[#24a394,dashed]-^  Proffesion                          
TraderHandler                        -[#3574f0,plain]->>  Herbs                               
TraderHandler                        -[#24a394,dashed]-^  IPersonActivity                     
TraderHandler                        -[#24a394,dashed]-^  ITraderHandler                      
TraderHandler                        -[#3574f0,plain]->>  Medicine                            
TraderHandler                        -[#3574f0,plain]->>  Threat                              
TraderHandler                        -[#3574f0,plain]->>  Weaponry                            
TraderHandler                        -[#3574f0,plain]->>  Wood                                
Weaponry                             -[#24a394,dashed]-^  Resource                            
Wood                                 -[#24a394,dashed]-^  Resource                            
init                                 -[#3574f0,plain]->>  ColonySimulatorContext              
@enduml
