@startuml
class BlackSmithHandler {
    + CreateWeapon(weapon:Weaponry, wood:Wood, blackLevel:int) : Task
    + ExperienceThreat(effect:Effect, proffesion:Proffesion, resources:List<Resource>) : Task
}
IBlackSmithHandler <|-- BlackSmithHandler

@enduml
