@startuml
class ProfessionHandler {
    + ProfessionHandler(farmerHandler:IFarmerHandler, apothecaryHandler:IApothecaryHandler, blackSmithHandler:IBlackSmithHandler, medicHandler:IMedicHandler, timberHandler:ITimberHandler, traderHandler:ITraderHandler, dbContext:ColonySimulatorContext, threatHandler:IThreatHandler, threatProvider:IThreatProvider)
    + <<async>> HandleFarm() : Task
    + <<async>> HandleApothecary() : Task
    + <<async>> HandleTimber() : Task
    + <<async>> HandleBlackSmith() : Task
    + <<async>> HandleMedic() : Task
    + <<async>> HandleTrader() : Task
}
IProfessionHandler <|-- ProfessionHandler
IFarmerHandler --* ProfessionHandler
IMedicHandler --* ProfessionHandler
IApothecaryHandler --* ProfessionHandler
IBlackSmithHandler --* ProfessionHandler
ITimberHandler --* ProfessionHandler
ITraderHandler --* ProfessionHandler
IThreatHandler --* ProfessionHandler
IThreatProvider --* ProfessionHandler
ColonySimulatorContext --* ProfessionHandler
@enduml
