@startuml
class TimberHandler {
    + CreateWood(wood:Wood, timLevel:int) : Task
    + ExperienceThreat(effect:Effect, proffesion:Proffesion, resources:List<Resource>) : Task
}
ITimberHandler <|-- TimberHandler

@enduml
