@startuml
class TraderHandler {
    + Trade(crops:Crops, wood:Wood, medicine:Medicine, herbs:Herbs, weaponry:Weaponry) : Task
    + ExperienceThreat(effect:Effect, proffesion:Proffesion, resources:List<Resource>) : Task
}
ITraderHandler <|-- TraderHandler
@enduml
