// <auto-generated />
using ColonySimulator.Backend.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColonySimulator.Backend.Migrations
{
    [DbContext(typeof(ColonySimulatorContext))]
    partial class ColonySimulatorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("ColonySimulator.Backend.Persistence.Models.Professions.Apothecary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApothecaryLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSick")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RequiredAgility")
                        .HasColumnType("REAL");

                    b.Property<double>("RequiredStrength")
                        .HasColumnType("REAL");

                    b.Property<double>("ResourceConsumption")
                        .HasColumnType("REAL");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vitality")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Apothecaries");
                });

            modelBuilder.Entity("ColonySimulator.Backend.Persistence.Models.Professions.BlackSmith", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlackSmithLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSick")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RequiredAgility")
                        .HasColumnType("REAL");

                    b.Property<double>("RequiredStrength")
                        .HasColumnType("REAL");

                    b.Property<double>("ResourceConsumption")
                        .HasColumnType("REAL");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vitality")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BlackSmiths");
                });

            modelBuilder.Entity("ColonySimulator.Backend.Persistence.Models.Professions.Farmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FarmingLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSick")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RequiredAgility")
                        .HasColumnType("REAL");

                    b.Property<double>("RequiredStrength")
                        .HasColumnType("REAL");

                    b.Property<double>("ResourceConsumption")
                        .HasColumnType("REAL");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vitality")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Farmers");
                });

            modelBuilder.Entity("ColonySimulator.Backend.Persistence.Models.Professions.Medic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSick")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicLevel")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RequiredAgility")
                        .HasColumnType("REAL");

                    b.Property<double>("RequiredStrength")
                        .HasColumnType("REAL");

                    b.Property<double>("ResourceConsumption")
                        .HasColumnType("REAL");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vitality")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Medics");
                });

            modelBuilder.Entity("ColonySimulator.Backend.Persistence.Models.Professions.Timber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSick")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RequiredAgility")
                        .HasColumnType("REAL");

                    b.Property<double>("RequiredStrength")
                        .HasColumnType("REAL");

                    b.Property<double>("ResourceConsumption")
                        .HasColumnType("REAL");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimberLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vitality")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Timbers");
                });

            modelBuilder.Entity("ColonySimulator.Backend.Persistence.Models.Professions.Trader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSick")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RequiredAgility")
                        .HasColumnType("REAL");

                    b.Property<double>("RequiredStrength")
                        .HasColumnType("REAL");

                    b.Property<double>("ResourceConsumption")
                        .HasColumnType("REAL");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TradingLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vitality")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Traders");
                });

            modelBuilder.Entity("ColonySimulator.Backend.Persistence.Models.Resources.Crops", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CropsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("ColonySimulator.Backend.Persistence.Models.Resources.Herbs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HerbsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Herbs");
                });

            modelBuilder.Entity("ColonySimulator.Backend.Persistence.Models.Resources.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicineCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("ColonySimulator.Backend.Persistence.Models.Resources.Weaponry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WeaponryCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Weaponry");
                });

            modelBuilder.Entity("ColonySimulator.Backend.Persistence.Models.Resources.Wood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WoodCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Wood");
                });

            modelBuilder.Entity("ColonySimulator.Backend.Persistence.Models.Threats.FightingThreat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredSmithingLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredWeaponryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThreatLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FightingThreats");
                });

            modelBuilder.Entity("ColonySimulator.Backend.Persistence.Models.Threats.NaturalThreat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredCropsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredFarmingLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThreatLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NaturalThreats");
                });

            modelBuilder.Entity("ColonySimulator.Backend.Persistence.Models.Threats.PlagueThreat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredMedicalLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredMedicineCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThreatLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PlagueThreats");
                });
#pragma warning restore 612, 618
        }
    }
}
