@startuml
abstract class Person {
    + Id : int <<get>> <<set>>
    + Vitality : double <<get>> <<set>>
    + Strength : double <<get>> <<set>>
    + Agility : double <<get>> <<set>>
    + ResourceConsumption : double <<get>> <<set>>
}
Person --> "Gender" Gender
@enduml
