@startuml
class ResourceHandler {
    + ResourceHandler(dbContext:ColonySimulatorContext)
    + <<async>> ConsumeResources(popCount:int) : Task
}
IResourceHandler <|-- ResourceHandler
ColonySimulatorContext --* ResourceHandler
@enduml
