@startuml
interface IApothecaryHandler {
    + CreateMedicine(herbs:Herbs, medicine:Medicine, apoLevel:int) : Task
    + CollectingHerbs(herbs:Herbs, apoLevel:int) : Task
}
IPersonActivity <|-- IApothecaryHandler
Medicine ..> IApothecaryHandler
Herbs ..> IApothecaryHandler

@enduml
