@startuml
interface IApothecaryHandler {
    + CreateMedicine(herbs:Herbs) : Task
    + CollectingHerbs(herbs:Herbs) : Task
}
IPersonActivity <|-- IApothecaryHandler
Herbs <.. IApothecaryHandler

@enduml
