@startuml
interface IBlackSmithHandler {
    + CreateWeapon(weapon:Weaponry, wood:Wood, blackLevel:int) : Task
}
IPersonActivity <|-- IBlackSmithHandler
IBlackSmithHandler <.. Weaponry
IBlackSmithHandler <.. Wood

@enduml
