@startuml
interface IMedicHandler {
    + Heal(medicine:Medicine, person:Person, medLevel:int) : Task
}
IPersonActivity <|-- IMedicHandler
Medicine ..> IMedicHandler
Person ..> IMedicHandler

@enduml
