@startuml
interface IProfessionHandler {
    + DoWork(proffesion:Proffesion) : Task
    + ExperienceThreat(effect:Effect) : Task
}

Proffesion <.. IProfessionHandler
Effect <.. IProfessionHandler
@enduml
