@startuml
interface ITraderHandler {
    + Trade(crops:Crops, wood:Wood, medicine:Medicine, herbs:Herbs, weaponry:Weaponry) : Task
}
IPersonActivity <|-- ITraderHandler
Crops ..> ITraderHandler
Wood ..> ITraderHandler
Medicine ..> ITraderHandler
Herbs ..> ITraderHandler
Weaponry ..> ITraderHandler
@enduml
