@startuml
interface IPersonActivity {
    + ExperienceThreat(effect:Effect, profession:Proffesion, resources:List<Resource>) : Task
}
Effect ..> IPersonActivity
Proffesion ..> IPersonActivity
Resource ..> IPersonActivity
@enduml
