@startuml
interface IThreatHandler {
    + CalculateAffection(proffesion:Proffesion) : Task
    + GenerateEffects(threat:Threat) : Task<Effect>
}

Proffesion <.. IThreatHandler
Threat <.. IThreatHandler
@enduml
