@startuml
class ColonySimulatorContext {
    + ColonySimulatorContext(options:DbContextOptions<ColonySimulatorContext>)
}

DbContext <|-- ColonySimulatorContext
Apothecary -- ColonySimulatorContext
Blacksmith -- ColonySimulatorContext
Farmer -- ColonySimulatorContext
Medic -- ColonySimulatorContext
Timber -- ColonySimulatorContext
Trader -- ColonySimulatorContext
Crops -- ColonySimulatorContext
Herbs -- ColonySimulatorContext
Medicine -- ColonySimulatorContext
Weaponry -- ColonySimulatorContext
Wood -- ColonySimulatorContext
@enduml
