@startuml
class ProfessionsOverview {
}

Apothecary --> ProfessionsOverview
Blacksmith --> ProfessionsOverview
Farmer --> ProfessionsOverview
Trader --> ProfessionsOverview
Medic --> ProfessionsOverview
Timber --> ProfessionsOverview
@enduml
