@startuml
class FightingThreatEffect {
    + FightingThreatEffect()
    + FightingThreatEffect(name:string, damage:int, resourcesStolen:List<Resource>)
}

Effect <|-- FightingThreatEffect
FightingThreatEffect ..> Resource
@enduml
