@startuml
class StartupService {
    + StartupService(logger:ILogger, serviceScope:IServiceScopeFactory, dataWriter:IEndDataWriter, simulationService:StartSimulationService)
    + <<async>> StartAsync(cancellationToken:CancellationToken) : Task
    + <<async>> StopAsync(cancellationToken:CancellationToken) : Task
}

StartSimulationService --o StartupService
IEndDataWriter --o StartupService
@enduml
