@startuml
class StartSimulationService {
    + StartSimulationService(serviceScopeFactory:IServiceScopeFactory, counter:PopCounter, year:Year, entityManagementService:IEntityManagementService, threatProvider:IThreatProvider, dataStorer:EndDataStorer)
    + <<async>> RunAsync(isManually:bool, ct:CancellationToken) : Task
}

PopCounter --o StartSimulationService
Year --o StartSimulationService
IEntityManagementService --o StartSimulationService
IThreatProvider --o StartSimulationService
EndDataStorer --o StartSimulationService

@enduml
